#!/bin/bash
echo "TEST Before plz work"
# rm /etc/apache2/sites-available/000-default.conf
# DIR="/home/ubuntu/django_app"
# if [ -d "$DIR" ]; then
#     echo "$DIR exists"
# else
#     echo "Creating $DIR directory"
#     mkdir $DIR
# fi

# sudo apt-get update
# sudo apt-get install python3-pip apache2 libapache2-mod-wsgi-py3 libmysqlclient-dev
# sudo pip3 install virtualenv
