# Generated by Django 3.2.6 on 2021-10-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donuts',
            options={'managed': False},
        ),
    ]
