# Generated by Django 3.2.6 on 2021-10-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0002_alter_donuts_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donuts',
            table='donuts',
        ),
    ]
