AWSTemplateFormatVersion: "2010-09-09"
Description: A Template for Deploying the Infrastructure for Group Project 3.
Parameters:
  SubnetID:
    Type: String
Resources:
  # myVPC:
  #     Type: AWS::EC2::VPC
  #     Properties:
  #       CidrBlock: 10.0.0.0/16
  #       EnableDnsSupport: 'true'
  #       EnableDnsHostnames: 'true'
  #       Tags:
  #         - Key: stack
  #           Value: production
  #         - Key: Name
  #           Value: project3-vpc
  # mySubnet:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId:
  #       Ref: myVPC
  #     AvailabilityZone: us-east-2a
  #     CidrBlock: 10.0.0.0/24
  #     Tags:
  #       - Key: Name
  #         Value: project3-subnet
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: project3-deployment-cluster
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: project3-deployment-log-group
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: project3-deployment-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      # Policies:
      #   - PolicyName: root
      #     PolicyDocument:
      #       Statement:
      #       - Effect: Allow
      #         Action: 
      #           - "ecr:BatchCheckLayerAvailability"
      #           - "ecr:BatchGetImage"
      #           - "ecr:GetDownloadUrlForLayer"
      #           - "ecr:GetAuthorizationToken"
      #         Resource: "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: ContainerSecurityGroup
      GroupDescription: Security Group for Project 3
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: project3-deployment-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: project3-deployment-container
          Image: 168880487690.dkr.ecr.us-east-2.amazonaws.com/chocolate-django-project:latest
          PortMappings:
            - ContainerPort: 8000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - EC2
        - FARGATE
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: project3-deployment-service
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration: 
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetID
          SecurityGroups: 
            - !GetAtt ContainerSecurityGroup.GroupId
        
